logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.alhas.airbnb: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-clone-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb_clone
  security:
    oauth2:
      client:
        registration:
          okta: # Identifiant unique pour votre fournisseur
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
            authorization-grant-type: authorization_code
            client-name: Okta
        provider:
          okta: # Informations sur le fournisseur Auth0
            issuer-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
# dev-lbu4c820m2nza8vh.us.auth0.com
okta:
  oauth2:
    issuer: https://dev-lbu4c820m2nza8vh.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    redirect-uri: "{baseUrl}/login/oauth2/code/okta"

application:
  auth0:
    role-landlord-id: rol_bMjiQLmAN3LUSbqi

